feat: add Datadog Logs output
falcosecurity/falcosidekick pull request #1056
Opened 2024-11-20 15:34 UTC by yohboy

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area outputs

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1052

**Special notes for your reviewer**:

2024-11-20 15:34 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/1056#" title="Author self-approved">yohboy</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign [fjogeleit](https://github.com/fjogeleit) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fjogeleit"]} -->

2024-11-21 12:31 UTC, Issif requested changes

2024-11-21 12:31 UTC, Issif commented on config_example.yaml
> +  # apikey: "" # Datadog API Key, if not empty, Datadog output is enabled
```suggestion
datadoglogs:
  # apikey: "" # Datadog API Key, if not empty, Datadog Logs output is enabled
```

2024-11-21 12:31 UTC, Issif commented on config_example.yaml
> +  # apikey: "" # Datadog API Key, if not empty, Datadog output is enabled
lower case for consistency

2024-11-21 12:31 UTC, Issif commented on docs/outputs/datadog_logs.md
> +| `datadogLogs.service`         | `DATADOG_LOGS_SERVICE`         | `""`            | The name of the application or service generating the log events. |
```suggestion
| `datadoglogs.apikey`          | `DATADOG_LOGS_APIKEY`          |                            | Datadog API Key, if not empty, Datadog Logs output is **enabled**                                                                      |
| `datadoglogs.host`            | `DATADOG_LOGS_HOST`            | `https://http-intake.logs.datadoghq.com/` | Datadog host. Override if you are on the Datadog EU site                                                                          |
| `datadoglogs.minimumpriority` | `DATADOG_LOGS_MINIMUMPRIORITY` | `""` (= `debug`)           | Minimum priority of event for using this output, order is `emergency,alert,critical,error,warning,notice,informational,debug or ""` |
| `datadoglogs.service`         | `DATADOG_LOGS_SERVICE`         | `""`            | The name of the application or service generating the log events. |
```

2024-11-21 12:31 UTC, Issif commented on docs/outputs/datadog_logs.md
> +  apikey: "" # Datadog API Key, if not empty, Datadog output is enabled
```suggestion
datadoglogs:
  apikey: "" # Datadog API Key, if not empty, Datadog Logs output is enabled
```

2024-11-21 12:31 UTC, Issif commented on outputs/datadog_logs.go
> +	c.OTLPMetrics.Outputs.With(attribute.String("destination", "datadogLogs"),
```suggestion
		go c.CountMetric(Outputs, 1, []string{"output:datadoglogs", "status:error"})
		c.Stats.DatadogLogs.Add(Error, 1)
		c.PromStats.Outputs.With(map[string]string{"destination": "datadoglogs", "status": Error}).Inc()
		c.OTLPMetrics.Outputs.With(attribute.String("destination", "datadoglogs"),
			attribute.String("status", Error)).Inc()
		log.Printf("[ERROR] : Datadog Logs - %v\n", err)
		return
	}

	go c.CountMetric(Outputs, 1, []string{"output:datadogLogs", "status:ok"})
	c.Stats.DatadogLogs.Add(OK, 1)
	c.PromStats.Outputs.With(map[string]string{"destination": "datadoglogs", "status": OK}).Inc()
	c.OTLPMetrics.Outputs.With(attribute.String("destination", "datadoglogs"),
```

2024-11-21 14:05 UTC, Issif approved these changes
thanks a lot :pray:

2024-11-21 14:05 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/1056#pullrequestreview-2451571464" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/1056#" title="Author self-approved">yohboy</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-11-21 14:05 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: cf6fb7f10f163ef7bcb845f940d4efe078d06482</details>

2024-11-21 15:02 UTC, merged

2024-11-21 15:04 UTC, yohboy commented
Thanks for your review ! 🚀