mattermost: add missing statds/dogstastd metrics
falcosecurity/falcosidekick pull request #153
Opened 2020-12-13 14:23 UTC by cpanato

**What type of PR is this?**
/kind cleanup

**Any specific area of the project related to this PR?**

/area outputs

**What this PR does / why we need it**:
mattermost: add missing statds/dogstastd metrics

**Which issue(s) this PR fixes**:

Fixes partially https://github.com/falcosecurity/falcosidekick/issues/144

**Special notes for your reviewer**:

/assign @Issif

2020-12-13 14:23 UTC, poiana commented
@cpanato: The label(s) `area/outputs` cannot be applied, because the repository doesn't have them

<details>

In response to [this](https://github.com/falcosecurity/falcosidekick/pull/153):

>**What type of PR is this?**
>/kind cleanup
>
>**Any specific area of the project related to this PR?**
>
>/area outputs
>
>**What this PR does / why we need it**:
>mattermost: add missing statds/dogstastd metrics
>
>**Which issue(s) this PR fixes**:
>
>
>
>Fixes partially https://github.com/falcosecurity/falcosidekick/issues/144
>
>**Special notes for your reviewer**:
>
>
>/assign @Issif 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2020-12-13 14:23 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leogr** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leogr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2020-12-13 14:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **issif** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @issif` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2020-12-17 21:55 UTC, Issif requested changes

2020-12-17 21:55 UTC, Issif commented on outputs/mattermost.go
> +			log.Printf("[ERROR] : Mattermost - Error expanding Slack message %v", err)
```suggestion
			log.Printf("[ERROR] : Mattermost - Error expanding Mattermost message %v", err)
```

2020-12-18 09:48 UTC, cpanato commented on outputs/mattermost.go
> +			log.Printf("[ERROR] : Mattermost - Error expanding Slack message %v", err)
🤦

2020-12-18 10:05 UTC, Issif approved these changes

2020-12-18 10:05 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: aa990bbec4bbbb3422cfb196085facdc43811c89</details>

2020-12-18 10:05 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/153#pullrequestreview-555354492" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-18 10:06 UTC, merged