Added output type s3
falcosecurity/falcosidekick pull request #195
Opened 2021-02-25 20:34 UTC by evalsocket

Signed-off-by: Yuvraj <evalsocket@gmail.com>

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

 /area outputs

 /area tests

**What this PR does / why we need it**:
Added new output type s3. Now you can upload json payload to s3 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-02-25 20:34 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leodido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leodido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leodido"]} -->

2021-02-25 20:34 UTC, poiana commented
Welcome @evalsocket! It looks like this is your first PR to falcosecurity/falcosidekick 🎉

2021-02-25 22:06 UTC, Issif requested changes

2021-02-25 22:06 UTC, Issif commented on outputs/aws.go
> +	if c.Config.AWS.S3.Prefix != "" {
You need to declare the config https://github.com/falcosecurity/falcosidekick/blob/master/config.go

2021-02-25 22:06 UTC, Issif commented on outputs/aws.go
> +		go c.CountMetric("outputs", 1, []string{"output:awss3", "status:error"})
you need to declare the stats in https://github.com/falcosecurity/falcosidekick/blob/master/stats.go

2021-02-25 22:06 UTC, Issif commented on outputs/aws.go
> +func (c *Client) UploadS3(falcopayload types.FalcoPayload) {
You need to declare the new client in https://github.com/falcosecurity/falcosidekick/blob/master/main.go

You need to declare the handler in https://github.com/falcosecurity/falcosidekick/blob/master/handlers.go

2021-02-25 22:40 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **issif** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @issif` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-02-25 22:40 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [5c81327](https://github.com/falcosecurity/falcosidekick/commits/5c81327d8460823f3efc15c46de71121b0ac8711) wip: added stats and handler for new output type

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-02-25 23:29 UTC, Issif requested changes

2021-02-25 23:29 UTC, Issif commented on config.go
> +	v.SetDefault("AWS.S3.Prefix", "falcosidekick")
```suggestion
	v.SetDefault("AWS.S3.Bucket", "")
	v.SetDefault("AWS.S3.Prefix", "falco")
	v.SetDefault("AWS.S3.MinimumPriority", "")
```

I prefer to keep same order than others and it's more logical to use `falco` as default prefix.

2021-02-25 23:29 UTC, Issif commented on handlers.go
> +		go awsClient.UploadS3(falcopayload)
```suggestion
		go awsClient.PublishTopic(falcopayload)
```

2021-02-25 23:29 UTC, Issif commented on handlers.go
> +		go awsClient.PublishTopic(falcopayload)
```suggestion
		go awsClient.UploadS3(falcopayload)
```

2021-02-25 23:29 UTC, Issif commented on main.go
> +			config.AWS.S3.Bucket = ""
For line #214 (I can't propose on a suggestion for sorry)

```go
if config.AWS.Lambda.FunctionName != "" || config.AWS.SQS.URL != "" ||
		config.AWS.SNS.TopicArn != "" || config.AWS.CloudWatchLogs.LogGroup != "" || config.AWS.S3.Bucket != ""
```

2021-02-25 23:29 UTC, Issif commented on outputs/aws.go
> +	key := fmt.Sprintf("%s/%s/%s.json", prefix, t.Format("2006-01-02"), t.Format("2006-01-02"))
```suggestion
	key := fmt.Sprintf("%s/%s/%s.json", prefix, t.Format("2006-01-02"), t.Format(time.RFC3339Nano))
```

2021-02-25 23:29 UTC, Issif commented on outputs/aws.go
> +		log.Printf("[DEBUG] : %v S3 - SSECustomerKeyMD5 : %v\n", c.OutputType, *resp.SSECustomerKeyMD5)
I'm not sure it's useful as we print the md5 in anycase (Line 168)

2021-02-26 21:40 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [a15cd3c](https://github.com/falcosecurity/falcosidekick/commits/a15cd3c9e6c5a3fb2306fc1e52e488384b485548) Small fixes

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-02-26 21:42 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [2bf8e7e](https://github.com/falcosecurity/falcosidekick/commits/2bf8e7ec1b2661ef7e6ac74df0ea5949213c261f) Small fixes

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-02-28 12:00 UTC, Issif reviewed
It seems OK for me, I'll make some tests before approving.

Can you update the `README` et `config_example.yaml`, please?

2021-02-28 19:39 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [f3b48fb](https://github.com/falcosecurity/falcosidekick/commits/f3b48fb14b1bb7a832894af25f7e4d01450df1a7) Added docs for aws s3 output type

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-02-28 19:52 UTC, Issif requested changes
I added some comments, and it remains `config_example.yaml` to update please

2021-02-28 19:52 UTC, Issif commented on README.md
> +    # prefix : "" # name of prefix
```suggestion
    # prefix : "" # name of prefix, keys will have format: s3://<bucket>/<prefix>/YYYY-MM-DD/YYYY-MM-DDTHH:mm:ss.s+01:00.json
```

2021-02-28 19:52 UTC, Issif commented on README.md
> +- **AWS_S3_PREFIX** : Prefix name of the object
```suggestion
- **AWS_S3_PREFIX** : Prefix name of the object, keys will have format: s3://<bucket>/<prefix>/YYYY-MM-DD/YYYY-MM-DDTHH:mm:ss.s+01:00.json
```

2021-03-01 01:14 UTC, Issif requested changes
Just add AWS S3 in the list of available outputs in README and we're good 👍

2021-03-02 07:50 UTC, evalsocket commented
@Issif README changes are done

2021-03-02 14:36 UTC, cpanato commented
/lgtm

thanks for this addition

2021-03-02 14:36 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: fdaf143c5a068e758a25bd38992a80cffb415b29</details>

2021-03-02 14:36 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/195#issuecomment-788953307" title="LGTM">cpanato</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [cpanato]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-02 15:11 UTC, Issif commented
> @Issif README changes are done

I can't see AWS S3 in List of available outputs 🤔

2021-03-02 15:15 UTC, poiana commented
New changes are detected. LGTM label has been removed.

2021-03-02 15:15 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [d6b420d](https://github.com/falcosecurity/falcosidekick/commits/d6b420d394fb34d5f21da799d0b1617def36c603) Updated output list in readme

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-03-02 16:14 UTC, Issif approved these changes

2021-03-02 16:14 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 966d98d929297f4bf1ef196bede23b0cfaaf111d</details>

2021-03-02 16:14 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/195#issuecomment-788953307" title="LGTM">cpanato</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/195#pullrequestreview-602001415" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif,cpanato]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-02 16:18 UTC, merged