[WIP] Added rabbitmq type
falcosecurity/falcosidekick pull request #210
Opened 2021-03-13 09:05 UTC by evalsocket

Signed-off-by: Yuvraj <evalsocket@gmail.com>

**What type of PR is this?**

> kind feature

**Any specific area of the project related to this PR?**

> area outputs

**What this PR does / why we need it**: Added new output type RabbitMQ

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-03-13 09:05 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leogr** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leogr` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leogr"]} -->

2021-03-13 09:05 UTC, poiana commented
@evalsocket: There is not a label identifying the kind of this PR.
Please specify it either using `/kind <group>` or manually from the side menu.


<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-14 12:05 UTC, poiana commented
@evalsocket: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-16 22:28 UTC, Issif requested changes
you have some linting issue to fix 😉

2021-03-16 22:28 UTC, Issif commented on config.go
> +	v.SetDefault("Rabbitmq.Queue", "")
```suggestion
	v.SetDefault("Rabbitmq.URL", "")
	v.SetDefault("Rabbitmq.Queue", "")
	v.SetDefault("Rabbitmq.MinimumPriority", "")
```

For keeping same order than others

2021-03-16 22:28 UTC, Issif commented on main.go
> +		rabbitmqClient, err = outputs.NewRabbitmqClient( config, stats, promStats, statsdClient, dogstatsdClient)
```suggestion
		rabbitmqClient, err = outputs.NewRabbitmqClient(config, stats, promStats, statsdClient, dogstatsdClient)
```

2021-03-16 22:28 UTC, Issif commented on main.go
> +			outputs.EnabledOutputs = append(outputs.EnabledOutputs, "Rabbitmq")
```suggestion
			outputs.EnabledOutputs = append(outputs.EnabledOutputs, "RabbitMQ")
```

2021-03-16 22:28 UTC, Issif commented on outputs/rabbitmq.go
> +// NewRabbitmqClient returns a new output.Client for accessing the Rabbitmqs API.
```suggestion
// NewRabbitmqClient returns a new output.Client for accessing the RabbitmMQ API.
```

2021-03-16 22:28 UTC, Issif commented on outputs/rabbitmq.go
> +			log.Printf("[ERROR] : Rabbitmq - %v\n", "Error while connecting rabbitmq")
```suggestion
			log.Printf("[ERROR] : RabbitMQ - %v\n", "Error while connecting rabbitmq")
```

2021-03-16 22:28 UTC, Issif commented on outputs/rabbitmq.go
> +		OutputType:      "GCP",
```suggestion
		OutputType:      "RabbitMQ",
```

2021-03-16 22:28 UTC, Issif commented on outputs/rabbitmq.go
> +	err := c.RabbitmqClient.Publish("", c.Config.Rabbitmq.Queue, false,false, amqp.Publishing {
```suggestion
	err := c.RabbitmqClient.Publish("", c.Config.Rabbitmq.Queue, false, false, amqp.Publishing {
```

2021-03-16 22:28 UTC, Issif commented on outputs/rabbitmq.go
> +	log.Printf("[INFO]  : rabbitmq - Send to message OK \n")
```suggestion
	log.Printf("[INFO]  : RabbitMQ - Send to message OK\n")
```

2021-03-25 17:49 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [b53f71b](https://github.com/falcosecurity/falcosidekick/commits/b53f71b2b66c474cb2ecd7f8883ce7d4328d26ac) wip: small fix

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-03-25 17:49 UTC, poiana commented
@evalsocket: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-25 17:49 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **issif** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-03-25 20:47 UTC, Issif approved these changes

2021-03-25 20:47 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 31f2fb1c1cd5a95cbe11c2db553168f0a4f17cfb</details>

2021-03-25 20:47 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/210#pullrequestreview-621564640" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-26 11:18 UTC, leogr reviewed
Hey,

this PR LGTM, thank you! :+1: 

However, there're merge commits which are not allowed in this repo, and all commits need to be [signed-off](https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

You can fix both with the following one-liner:
```
git rebase -i --exec 'git commit --amend --no-edit -n -s -S' master
```
(and resolve conflicts, if any)
Finally, you can `git push --force-with-lease` your branch to update this PR.


Thanks in advance, and let me know if you need any support with that.

2021-03-26 18:32 UTC, poiana commented
New changes are detected. LGTM label has been removed.

2021-03-26 18:32 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **issif** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-03-26 18:32 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **issif** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-03-26 21:39 UTC, Issif approved these changes

2021-03-26 21:39 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: b39495780c2b118cba51eec62d9d823fc8f3b207</details>

2021-03-26 21:39 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/210#pullrequestreview-622550633" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-03-26 21:41 UTC, merged