[W.I.P]: add Google Cloud Functions output type
falcosecurity/falcosidekick pull request #241
Opened 2021-05-20 19:53 UTC by developer-guy

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

**What type of PR is this?**

> /kind design

> /kind documentation

> /kind feature

**Any specific area of the project related to this PR?**

> /area outputs

**What this PR does / why we need it**:

I thought that it would be nice if we have support for Cloud Function as an output type within the Falcosidekick.

**Which issue(s) this PR fixes**:

Fixes #240 

**Special notes for your reviewer**:

2021-05-20 19:53 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **developer-guy** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["developer-guy"]} -->

2021-05-20 19:53 UTC, poiana commented
@developer-guy: There is not a label identifying the kind of this PR.
Please specify it either using `/kind <group>` or manually from the side menu.


<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-05-20 19:59 UTC, developer-guy commented
@cartyc @cpanato Would you mind to review this PR? 🙏  We can add workload identity authentication support for it too, once your PR gets merged into the master @cartyc.

cc: @Issif

2021-05-20 20:01 UTC, Issif commented on README.md
> +    name: "" # The name of the Cloud Function
`minimumpriority` is missing

2021-05-20 20:11 UTC, cartyc commented
@developer-guy I'll try to take a look at it tonight/tomorrow. Looking forward to giving this a try :)

2021-05-20 21:32 UTC, Issif requested changes

2021-05-20 21:32 UTC, Issif commented on outputs/client.go
> +	functions "cloud.google.com/go/functions/apiv1"
```suggestion
	gcpfunctions "cloud.google.com/go/functions/apiv1"
```
I prefer this naming to avoid confusion

2021-05-20 21:32 UTC, Issif commented on outputs/client.go
>  	KafkaProducer     *kafka.Writer
```suggestion
	OutputType              string
	EndpointURL             *url.URL
	MutualTLSEnabled        bool
	CheckCert               bool
	Config                  *types.Configuration
	Stats                   *types.Statistics
	PromStats               *types.PromStatistics
	AWSSession              *session.Session
	StatsdClient            *statsd.Client
	DogstatsdClient         *statsd.Client
	GCPTopicClient          *pubsub.Topic
	GCPCloudFunctionsClient *functions.CloudFunctionsClient
	GCSStorageClient        *storage.Client
	KafkaProducer           *kafka.Writer
```

2021-05-21 00:11 UTC, cartyc commented
Looks good! Awesome work @developer-guy !!

2021-05-21 14:41 UTC, developer-guy commented on outputs/client.go
> +	functions "cloud.google.com/go/functions/apiv1"
done

2021-05-21 14:41 UTC, developer-guy commented on README.md
> +    name: "" # The name of the Cloud Function
done

2021-05-21 15:03 UTC, Issif submitted a review, later dismissed

2021-05-21 15:03 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 9f532b146da87331e293f96e0abc12180b938c40</details>

2021-05-21 15:03 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/241#pullrequestreview-665566153" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-21 15:51 UTC, poiana commented
New changes are detected. LGTM label has been removed.

2021-05-21 15:51 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **developer-guy** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["developer-guy"]} -->

2021-05-21 15:51 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **developer-guy** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["developer-guy"]} -->

2021-05-22 09:35 UTC, developer-guy commented
/kind feature

2021-05-22 16:02 UTC, Issif approved these changes

2021-05-22 16:02 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: eefe4d4d1c84950363a21ded9a39f1d66bd321cd</details>

2021-05-22 16:02 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/241#pullrequestreview-666192906" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-05-22 16:05 UTC, merged