Yandex S3 output
falcosecurity/falcosidekick pull request #261
Opened 2021-08-04 12:30 UTC by nar3k

- Added Yandex S3 output
- fixed GoLint error

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

https://github.com/falcosecurity/falcosidekick/issues/258

Fixes #

**Special notes for your reviewer**:

2021-08-04 12:30 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/261#" title="Author self-approved">nar3k</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **leodido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @leodido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leodido"]} -->

2021-08-04 12:56 UTC, nar3k commented
/assign @leodido

2021-08-04 18:50 UTC, Issif requested changes

2021-08-04 18:50 UTC, Issif commented on main.go
> +	yandexS3Client      *outputs.Client
```suggestion
	yandexClient      *outputs.Client
```

The client will be used for both S3 and Log

2021-08-04 18:50 UTC, Issif commented on main.go
> +		yandexS3Client, err = outputs.NewYandexS3Client(config, stats, promStats, statsdClient, dogstatsdClient)
```suggestion
		yandexClient, err = outputs.NewYandexClient(config, stats, promStats, statsdClient, dogstatsdClient)
```

See my previous comment

2021-08-04 18:50 UTC, Issif commented on main.go
> +			log.Printf("[ERROR] : Yandex - %v\n", err)
```suggestion
            config.Yandex.S3.Bucket = ""
			log.Printf("[ERROR] : Yandex - %v\n", err)
```

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +func NewYandexS3Client(config *types.Configuration, stats *types.Statistics, promStats *types.PromStatistics, statsdClient, dogstatsdClient *statsd.Client) (*Client, error) {
```suggestion
// NewYandexClient returns a new output.Client for accessing the Yandex API.
func NewYandexClient(config *types.Configuration, stats *types.Statistics, promStats *types.PromStatistics, statsdClient, dogstatsdClient *statsd.Client) (*Client, error) {
```

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +		err2 := os.Setenv("AWS_SECRET_ACCESS_KEY", config.Yandex.SecretAccessKey)
if both AWS and Yandex are used, there will be a conflict. Is Yandex also able to use different keys?

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +			log.Printf("[ERROR] : AWS - Error setting AWS env vars")
```suggestion
			log.Printf("[ERROR] : Yandex - Error setting Yandex env vars")
```

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +			return nil, errors.New("Error setting AWS env vars")
```suggestion
			return nil, errors.New("Error setting Yandex env vars")
```

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +	log.Printf("[INFO] : Yandex S3 session has been configured successfully")
```suggestion
```

Not useful as lack of error message means it's ok

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +		return nil, errors.New("Error while creating AWS Session")
```suggestion
		log.Printf("[ERROR] : AWS - %v\n", "Error while creating Yandex Session")
		return nil, errors.New("Error while creating Yandex Session")
```

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +		OutputType:      "YandexS3",
```suggestion
		OutputType:      "Yandex",
```

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +// UploadS3 upload payload to S3
```suggestion
// UploadYandexS3 uploads payload to Yandex S3
```

2021-08-04 18:50 UTC, Issif commented on README.md
> +    # bucket: "falcosidekick" # AWS S3, bucket name
```suggestion
    # bucket: "falcosidekick" # Yandex S3, bucket name
```

2021-08-04 18:50 UTC, Issif commented on main.go
> +				outputs.EnabledOutputs = append(outputs.EnabledOutputs, "YandexS3Client")
```suggestion
				outputs.EnabledOutputs = append(outputs.EnabledOutputs, "YandexS3")
```

2021-08-04 18:50 UTC, Issif commented on main.go
> +	}
```suggestion
    }
	log.Printf("[INFO]  : Enabled Outputs : %s\n", outputs.EnabledOutputs)
```

2021-08-04 18:50 UTC, Issif commented on main.go
>  		log.Printf("[INFO]  : Enabled Outputs : %s\n", outputs.EnabledOutputs)
```suggestion
		log.Printf("[INFO]  : Enabled Outputs : %s\n", outputs.EnabledOutputs)
```

My bad, this line should not be there

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +		c.PromStats.Outputs.With(map[string]string{"destination": "awss3", "status": Error}).Inc()
```suggestion
		go c.CountMetric("outputs", 1, []string{"output:yandexs3", "status:error"})
		c.PromStats.Outputs.With(map[string]string{"destination": "yandexs3", "status": Error}).Inc()
```

2021-08-04 18:50 UTC, Issif commented on outputs/yandex.go
> +	c.PromStats.Outputs.With(map[string]string{"destination": "awss3", "status": "ok"}).Inc()
```suggestion
	go c.CountMetric("outputs", 1, []string{"output:yandexs3", "status:ok"})
	c.PromStats.Outputs.With(map[string]string{"destination": "yandexs3", "status": "ok"}).Inc()
```

2021-08-04 18:50 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/261#" title="Author self-approved">nar3k</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **leodido** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["leodido"]} -->

2021-08-05 10:31 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/261#" title="Author self-approved">nar3k</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **issif** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-08-05 16:40 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [a4c5848](https://github.com/falcosecurity/falcosidekick/commits/a4c584866e7db1c567fa37af7d87f6d05e064dc1) Fixed suggestions from PR

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-08-05 16:54 UTC, poiana commented
@nar3k: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-08-05 16:54 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [a4c5848](https://github.com/falcosecurity/falcosidekick/commits/a4c584866e7db1c567fa37af7d87f6d05e064dc1) Fixed suggestions from PR
- [68c6bc8](https://github.com/falcosecurity/falcosidekick/commits/68c6bc87431c7fab8bb70b5394c4b0e503b228e7) Merge branch 'Yandex-S3-new' of github.com:nar3k/falcosidekick into Yandex-S3-new

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-08-05 17:01 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [a4c5848](https://github.com/falcosecurity/falcosidekick/commits/a4c584866e7db1c567fa37af7d87f6d05e064dc1) Fixed suggestions from PR
- [68c6bc8](https://github.com/falcosecurity/falcosidekick/commits/68c6bc87431c7fab8bb70b5394c4b0e503b228e7) Merge branch 'Yandex-S3-new' of github.com:nar3k/falcosidekick into Yandex-S3-new

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-08-05 17:26 UTC, Issif requested changes

2021-08-05 17:26 UTC, Issif commented on README.md
> +    # minimumpriority: "" # minimum priority of event for using this output, order is emergency|alert|critical|erro
OK for me, can you also add these values into env vars section of README. please

2021-08-05 17:26 UTC, Issif commented on config.go
> +	c.Yandex.S3.MinimumPriority = checkPriority(c.Wavefront.MinimumPriority)
```suggestion
	c.Yandex.S3.MinimumPriority = checkPriority(c.Yandex.S3.MinimumPriority)
```

2021-08-05 17:26 UTC, Issif commented on main.go
> +	yandexClient      *outputs.Client
```suggestion
	yandexClient        *outputs.Client
```

2021-08-05 17:26 UTC, Issif commented on outputs/yandex.go
> +	}
I don't understand the purpose of this, why are you creating an `.aws/config` file? Can't you use env vars like for AWS Client?
Please, do not write anything on disk, keep everything in memory.

If it's just for avoiding a conflict with AWS credentials aside, you can create use this function for setting `Credentials`: [credential.NewStaticCredentials](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/#NewStaticCredentials)

2021-08-05 19:08 UTC, nar3k commented
I hope it should be fine right now

Sorry for the spam , im new to github community - this PR gave me a lot of experience

2021-08-05 19:29 UTC, Issif commented
> I hope it should be fine right now
> 
> Sorry for the spam , im new to github community - this PR gave me a lot of experience

No problem, I'm here for helping you to contribute.

2021-08-05 19:35 UTC, Issif requested changes

2021-08-05 19:35 UTC, Issif commented on README.md
> +- **YANDEX_S3_ENDPOINT**: yandex storage endpoint (default: https://storage.yandexcloud.net)
```suggestion
- **YANDEX_SECRETACCESSKEY** : Yandex Secret Access Key 
- **YANDEX_REGION**: Yandex region (default: ru-central-1)
- **YANDEX_S3_ENDPOINT**: Yandex storage endpoint (default: https://storage.yandexcloud.net) 
```

2021-08-06 07:38 UTC, Issif approved these changes
well done and congrats 👍

2021-08-06 07:38 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: d3a32b5c15bb3c2e1119824c93f41e39b6b601f1</details>

2021-08-06 07:38 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/261#pullrequestreview-724071353" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/261#" title="Author self-approved">nar3k</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-06 07:38 UTC, merged