Add KafkaRest as new output for Falco Sidekick
falcosecurity/falcosidekick pull request #263
Opened 2021-08-05 20:56 UTC by dirien

Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

**What type of PR is this?**

Fixes #262 

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:
The Kafka REST Proxy provides a RESTful interface to a Apache Kafka cluster, making it easy to produce and consume messages, view the state of the cluster, and perform administrative actions without using the native Kafka protocol or clients.

**Which issue(s) this PR fixes**:  #262 

Fixes #262 

**Special notes for your reviewer**:

2021-08-05 20:56 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/263#" title="Author self-approved">dirien</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **nibalizer** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @nibalizer` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["nibalizer"]} -->

2021-08-05 20:56 UTC, poiana commented
Welcome @dirien! It looks like this is your first PR to falcosecurity/falcosidekick 🎉

2021-08-05 21:04 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [5a0e7ce](https://github.com/falcosecurity/falcosidekick/commits/5a0e7ceb22c794122eeeb6ac493913e698dcf27d) Add KafkaRest as new output for Falco Sidekick

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-08-05 21:09 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [e4bb41f](https://github.com/falcosecurity/falcosidekick/commits/e4bb41f826b7090343c9633de7e7aebf4bf1618f) Add KafkaRest as new output for Falco Sidekick

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-08-05 22:22 UTC, Issif commented
Thank you very much, this is a very valuable PR, with a really nice description. I'll review asap but a first look tells me it's already really good.

👍

2021-08-06 07:54 UTC, Issif requested changes

2021-08-06 07:54 UTC, Issif commented on config.go
> +	c.KafkaRest.MinimumPriority = checkPriority(c.Kafka.MinimumPriority)
```suggestion
	c.KafkaRest.MinimumPriority = checkPriority(c.KafkaRest.MinimumPriority)
```

2021-08-06 07:54 UTC, Issif commented on main.go
> +			outputs.EnabledOutputs = append(outputs.EnabledOutputs, "Kafka Rest")
```suggestion
			outputs.EnabledOutputs = append(outputs.EnabledOutputs, "KafkaRest")
```
outputs are separated by a space when we print the list, this is why we need a string in camel case

2021-08-06 07:54 UTC, Issif commented on outputs/kafkarest.go
> +		c.setKafkaErrorMetrics()
```suggestion
	    c.Stats.KafkaRest.Add(Error, 1)
		c.PromStats.Outputs.With(map[string]string{"destination": "kafkarest", "status": Error}).Inc()
```

2021-08-06 08:23 UTC, poiana commented
@dirien: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-08-06 08:23 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [016781b](https://github.com/falcosecurity/falcosidekick/commits/016781b6336824364140de2878dff4c838e85638) Merge branch 'falcosecurity:master' into kafkarest

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-08-06 08:23 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/263#" title="Author self-approved">dirien</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **issif** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-08-06 08:40 UTC, dirien commented
@Issif, Thanks for the feedback. I changed everything according to your suggestions. looking forward. 😄

2021-08-06 08:44 UTC, Issif requested changes
Only 1 thing is missing, can you add your output in this [list](https://github.com/falcosecurity/falcosidekick#message-queue--streaming) please

2021-08-06 08:48 UTC, dirien commented
@Issif, done :) during the  Yandex rebase it must slipped through 😓

2021-08-06 14:47 UTC, Issif approved these changes
Congrats and thank you !!

2021-08-06 14:47 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: c9f7536a6b043e7ccb6bc9a8b98d10a4f984ab63</details>

2021-08-06 14:47 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/263#" title="Author self-approved">dirien</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/263#pullrequestreview-724436636" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-11 19:33 UTC, merged