prepare v2.24.0
falcosecurity/falcosidekick pull request #266
Opened 2021-08-12 19:13 UTC by Issif

Signed-off-by: Issif <issif_github@gadz.org>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

This PR is for release v2.24.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-08-12 19:13 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/266#" title="Author self-approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-12 19:50 UTC, Issif commented
/hold

2021-08-12 19:50 UTC, Issif commented
/do-not-merge/hold

2021-08-13 08:06 UTC, developer-guy requested changes

2021-08-13 08:06 UTC, developer-guy commented on CHANGELOG.md
> +- New output : **Alert Manager**
whitespace here :)

2021-08-13 08:06 UTC, developer-guy commented on CHANGELOG.md
> +- New output: **Fission** ([PR#255](https://github.com/falcosecurity/falcosidekick/pull/254) thanks to [@gauravgahlot](https://github.com/gauravgahlot))
I think there is a wrong reference here, it should be https://github.com/falcosecurity/falcosidekick/pull/255.

2021-08-13 11:46 UTC, developer-guy approved these changes

2021-08-13 11:46 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: b61c73e64fffa713f3323a15079b7277fc142370</details>

2021-08-13 11:46 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/266#pullrequestreview-729533612" title="Approved">developer-guy</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/266#" title="Author self-approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif,developer-guy]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-13 16:10 UTC, poiana commented
New changes are detected. LGTM label has been removed.

2021-08-13 16:10 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/266#" title="Author self-approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-13 16:10 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/266#" title="Author self-approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-16 06:28 UTC, developer-guy requested changes

2021-08-16 06:28 UTC, developer-guy commented on CHANGELOG.md
> +- Docker image is now availagle on [`AWS ECR Public Gallery`](https://gallery.ecr.aws/falcosecurity/falcosidekick) ([PR#265](https://github.com/falcosecurity/falcosidekick/pull/265) thanks to [@maxgi
`availagle`, typo in this word.

2021-08-16 09:04 UTC, developer-guy approved these changes
LGTM

2021-08-16 09:04 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 02ce023e683270cbb8bcf51a4d5ab1033079cfff</details>

2021-08-16 09:04 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/266#pullrequestreview-730485044" title="Approved">developer-guy</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/266#" title="Author self-approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif,developer-guy]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-16 09:04 UTC, merged