Fix Readme typo
falcosecurity/falcosidekick pull request #279
Opened 2021-11-08 09:38 UTC by Jujuyeh

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

/kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

> /area outputs

> /area tests

**What this PR does / why we need it**:

Fix a word typo in the README file. `ecossytem > ecosystem`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2021-11-08 09:38 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [3e46442](https://github.com/falcosecurity/falcosidekick/commits/3e46442aca19134478f1432c8168167b357cf275) Fix Readme typo

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2021-11-08 09:38 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/279#" title="Author self-approved">Jujuyeh</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **issif** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @issif` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2021-11-08 09:38 UTC, poiana commented
Welcome @Jujuyeh! It looks like this is your first PR to falcosecurity/falcosidekick 🎉

2021-11-08 09:43 UTC, cpanato requested changes
thanks for your PR, can you please sign the DCO?

2022-02-06 10:12 UTC, poiana commented
Issues go stale after 90d of inactivity.

Mark the issue as fresh with `/remove-lifecycle stale`.

Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

Provide feedback via https://github.com/falcosecurity/community.

/lifecycle stale

2022-03-02 17:56 UTC, Issif commented
I'm closing this PR, as #299 fixed same typo

2022-03-02 17:56 UTC, closed without merging