Add Alerta Output
falcosecurity/falcosidekick pull request #311
Opened 2022-04-12 01:40 UTC by LivingInSyn

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

This PR allows post events to Alerta (https://alerta.io/) 

**Special notes for your reviewer**:

Alerta API reference: https://docs.alerta.io/api/reference.html#alerts

2022-04-12 01:40 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [209c04d](https://github.com/falcosecurity/falcosidekick/commits/209c04d0d5c4b83db8086c307c305f8583a56292) add alerta payload struct
- [78f17ad](https://github.com/falcosecurity/falcosidekick/commits/78f17ad2cbdda59fd9d464a54214cef1517ca4b7) create alerta payload
- [9858190](https://github.com/falcosecurity/falcosidekick/commits/98581904b1dbbdbb4854345ff523ea858f851a7e) passing unit tests

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2022-04-12 01:40 UTC, poiana commented
Welcome @LivingInSyn! It looks like this is your first PR to falcosecurity/falcosidekick 🎉

2022-04-12 01:40 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/311#" title="Author self-approved">LivingInSyn</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **issif** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @issif` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2022-04-12 08:27 UTC, Issif requested changes

2022-04-12 08:27 UTC, Issif commented on outputs/alerta.go
> +		go c.CountMetric(Outputs, 1, []string{"output:alertmanager", "status:error"})
```suggestion
		go c.CountMetric(Outputs, 1, []string{"output:alerta", "status:error"})
```

2022-04-12 08:27 UTC, Issif commented on outputs/alerta.go
> +	c.Stats.Alertmanager.Add(Total, 1)
```suggestion
	c.Stats.Alerta.Add(Total, 1)
```

2022-04-12 08:27 UTC, Issif commented on outputs/alerta.go
> +		c.Stats.Alertmanager.Add(Error, 1)
```suggestion
		c.Stats.Alerta.Add(Error, 1)
```

2022-04-12 08:27 UTC, Issif commented on outputs/alerta.go
> +	c.Stats.Alertmanager.Add(OK, 1)
```suggestion
	c.Stats.Alerta.Add(OK, 1)
```

2022-04-12 12:56 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/311#" title="Author self-approved">LivingInSyn</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **issif** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2022-04-12 12:57 UTC, LivingInSyn commented
@Issif fixed alertmanager-> alerta issues, that's what I get for not waiting until the next morning to submit the PR, sorry about that

2022-04-14 15:45 UTC, Issif requested changes

2022-04-14 15:45 UTC, Issif commented on handlers.go
> +	if config.Alerta.Address != "" && (falcopayload.Priority >= types.Priority(config.Cliq.MinimumPriority) || falcopayload.Rule == testRule) {
```suggestion
	if config.Alerta.Address != "" && (falcopayload.Priority >= types.Priority(config.Alerta.MinimumPriority) || falcopayload.Rule == testRule) {
```

2022-04-14 16:06 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falcosidekick/blob/master/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [326b871](https://github.com/falcosecurity/falcosidekick/commits/326b871616e8dbe19a6f8cd00b2af19a40d3bfb3) Update handlers.go

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2022-04-14 16:14 UTC, Issif reviewed
Seems OK to me, can you squash your commits please, I'll approve then

2022-04-16 22:12 UTC, LivingInSyn commented
I'm closing this PR due to discovered issues in Alerta and inconsistent rules in their API between versions and in their docs. I no longer think Alerta is stable enough to not break

2022-04-16 22:12 UTC, closed without merging