Add Dynatrace output
falcosecurity/falcosidekick pull request #575
Opened 2023-07-31 10:29 UTC by blu3r4y

**What type of PR is this?**

/kind feature

**Any specific area of the project related to this PR?**

/area outputs

**What this PR does / why we need it**:

Adds [Dynatrace](http://dynatrace.com/) output to falcosidekick.

2023-07-31 10:29 UTC, poiana commented
Welcome @blu3r4y! It looks like this is your first PR to falcosecurity/falcosidekick 🎉

2023-07-31 10:29 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/575#" title="Author self-approved">blu3r4y</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign cpanato for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["cpanato"]} -->

2023-07-31 10:54 UTC, Issif commented
I'm in PTO this week, I will review this later when I'm back. FYI, I released a new version few days ago, I don't know when the next one will be out. Do you need this integration asap?

2023-07-31 11:06 UTC, blu3r4y commented
Hi @Issif, thanks for your quick response. We would like to announce this in a blog post within the next two weeks. Having a (pre-)release within the next couple of weeks would be awesome!! No hurry for now, enjoy your PTO, see you next week :)

2023-08-01 18:43 UTC, Issif commented
@blu3r4y I'll do my best to have a 2.29.0-rc1 next week. This is a great news, if you need anything for your blog post, tell me, that's my job to help you. If you agree, you could also propose a post for falco.org or even better, participate in our use-case section.

2023-08-01 18:50 UTC, Issif requested changes

2023-08-01 18:50 UTC, Issif commented on README.md
> +- **DYNATRACE_APITOKEN** : Dynatrace API token with the "logs.ingest" scope, more info : https://dt-url.net/8543sda
```suggestion
- **DYNATRACE_APITOKEN** : Dynatrace API token with the "logs.ingest" scope, more info : https://dt-url.net/8543sda, if not empty, Dynatrace output is enabled 
```

2023-08-01 18:50 UTC, Issif commented on config_example.yaml
> +  apitoken: "" # Dynatrace API token with the "logs.ingest" scope, more info : https://dt-url.net/8543sda
```suggestion
  apitoken: "" # Dynatrace API token with the "logs.ingest" scope, more info : https://dt-url.net/8543sda, if not empty, Dynatrace output is enabled 
```

2023-08-01 18:50 UTC, Issif commented on config_example.yaml
> +  # minimumpriority: "" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
the `checkcert ` is missing here but declared in the struct and at client creation

2023-08-01 21:52 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/575#" title="Author self-approved">blu3r4y</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from issif. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2023-08-01 22:13 UTC, blu3r4y commented
> @blu3r4y I'll do my best to have a 2.29.0-rc1 next week. This is a great news, if you need anything for your blog post, tell me, that's my job to help you. If you agree, you could also propose a post for falco.org or even better, participate in our use-case section.

@Issif Awesome, thanks! Also, we do plan additional content in that direction. I will make sure to reach out when we get there.

One specific question: We would love to use the Falco logo in the header for our blog post. As long as we comply with the CNCF brand guidelines this should be fine, right?

2023-08-02 00:10 UTC, Issif commented
Thank you.

For the logo, feel free to use it as you want, you can find the assets here: https://falco.org/community/falco-brand/

2023-08-02 16:58 UTC, Issif approved these changes
:+1:

2023-08-02 16:58 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: 79725718940b332bb2e4c6e6f6948022100c8a5f</details>

2023-08-02 16:59 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/575#" title="Author self-approved">blu3r4y</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/575#pullrequestreview-1559472203" title="Approved">Issif</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-08-02 17:08 UTC, merged

2023-08-02 19:14 UTC, Issif commented
@blu3r4y Here's the release candidate https://github.com/falcosecurity/falcosidekick/releases/tag/2.29.0-rc.1

2023-08-02 20:50 UTC, blu3r4y commented
@Issif This is awesome, thanks you so much for your swift assistance! 🥳