New output type: Webex
falcosecurity/falcosidekick pull request #979
Opened 2024-08-27 20:51 UTC by k0rventen

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

/kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area build

> /area config

/area outputs

> /area tests

**What this PR does / why we need it**:

This PR adds the 'Webex' output, enabling sending messages to a given Webex Room using a Webhook URL. As the format expected by the [Webex API endpoint](https://developer.webex.com/docs/api/v1/messages/create-a-message) is very specific, using the Webhook output isn't possible. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

I've taken inspiration from the Teams output, which is quite similar, which is why I placed the various Webex declarations right below it. If you prefer another order, let me know. 

I've tested it sucessfully using the provided curls's tests commands, and a few falco rules of my own.
Also let me now if I missed some docs/example ? 

Regards !

2024-08-27 20:51 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [5f77a47](https://github.com/falcosecurity/falcosidekick/commits/5f77a47a2963bcff6d5df006d25426e5adb925ac) feat: add webex output code
- [01b5f7f](https://github.com/falcosecurity/falcosidekick/commits/01b5f7f52ea7395ccc64fbdf78040397a188eb5b) feat: add webex related docs
- [6b854f3](https://github.com/falcosecurity/falcosidekick/commits/6b854f3972e0137ebe3f08fd0190ffc2f6baca2a) feat: add example config for webex
- [11e4ed5](https://github.com/falcosecurity/falcosidekick/commits/11e4ed514adebd860bbe3c58951b25923e7ad4d1) fix: remove duplicated headers

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2024-08-27 20:51 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/979#" title="Author self-approved">k0rventen</a>*
**Once this PR has been reviewed and has the lgtm label**, please assign [issif](https://github.com/issif) for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2024-08-27 20:51 UTC, poiana commented
Welcome @k0rventen! It looks like this is your first PR to falcosecurity/falcosidekick 🎉

2024-08-27 21:03 UTC, poiana commented
Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.

:memo: **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/.github/blob/main/CONTRIBUTING.md) to update your commits with the DCO**

Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).

**The list of commits missing DCO signoff**:

- [a409bdd](https://github.com/falcosecurity/falcosidekick/commits/a409bdd197aedb226f68069b002317e4b7bddb33) feat: add webex output code

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

2024-08-27 21:25 UTC, Issif commented
Amazing proposal, and it seems very complete. I will do the full review asap. Thanks

2024-09-02 18:40 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/979#" title="Author self-approved">k0rventen</a>*
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from [issif](https://github.com/issif). For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["issif"]} -->

2024-09-02 18:44 UTC, k0rventen commented
> Amazing proposal, and it seems very complete. I will do the full review asap. Thanks

Hey thx ! I just pushed a few fixes, apparently I forgot to check if I changed 'teams' to 'webex' everywhere. Also an improvement on the template loading, which is now done only once instead of on every call of the post function (not a go expert but I think it's better ?)

Cheers !

2024-09-02 18:52 UTC, Issif requested changes

2024-09-02 18:52 UTC, Issif commented on config_example.yaml
> +  #minimumpriority: "" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
```suggestion
  # webhookurl: "" # Webex WebhookURL, if not empty, Teams Webex is enabled
  # minimumpriority: "" # minimum priority of event for using this output, order is emergency|alert|critical|error|warning|notice|informational|debug or "" (default)
```

2024-09-02 18:52 UTC, Issif commented on docs/outputs/webex.md
> +
```suggestion
```

2024-09-02 18:52 UTC, Issif commented on docs/outputs/webex.md
> +| `teams.webhookurl`      | `TEAMS_WEBHOOKURL`      |                                                                                                     | Teams WebhookURL, if not empty, Teams outpu
```suggestion
| `wexeb.webhookurl`      | `WEBEX_WEBHOOKURL`      |                                                                                                     | Teams WebhookURL, if not empty, Webex output is **enabled** |
```

2024-09-02 18:52 UTC, Issif commented on outputs/webex.go
> +var tmpl, _ = template.New("markdown").Parse(md)
```suggestion
var webexTmpl, _ = template.New("markdown").Parse(md)
```

2024-09-02 18:52 UTC, Issif commented on outputs/webex.go
> +	if err := tmpl.Execute(&tpl, falcopayload); err != nil {
```suggestion
	if err := webexTmpl.Execute(&tpl, falcopayload); err != nil {
```

2024-09-02 19:14 UTC, k0rventen commented
> could you also squash your commits once you fixed my comments, please

We should be good now !

2024-09-02 19:26 UTC, Issif commented
> > could you also squash your commits once you fixed my comments, please
> 
> We should be good now !

Just the squash to do and I'll approve. Thanks

2024-09-03 16:13 UTC, Issif commented
> > > > could you also squash your commits once you fixed my comments, please
> > > 
> > > 
> > > We should be good now !
> > 
> > 
> > Just the squash to do and I'll approve. Thanks
> 
> yeah sorry when squashing I rewrote the commit message, leading to this one: [0db1a5f](https://github.com/falcosecurity/falcosidekick/commit/0db1a5f7161495d9add6329a1af75968d1b23a35)

the 6 commits are still there, most of them are typo fixes, rebase on the master then squash (rebase -i) your commits on the HEAD/master please

2024-09-03 19:50 UTC, k0rventen commented
it's now all in 19a6aac7688860b778731152d4a8f0ba3cd93acb :smile:

2024-09-03 19:53 UTC, Issif requested changes

2024-09-03 19:53 UTC, Issif commented on docs/outputs/webex.md
> +| `wexeb.webhookurl`      | `WEBEX_WEBHOOKURL`      |                                                                                                     | Teams WebhookURL, if not empty, Webex outpu
```suggestion
| `webex.webhookurl`      | `WEBEX_WEBHOOKURL`      |                                                                                                     | Teams WebhookURL, if not empty, Webex output is **enabled** |
```

2024-09-03 19:53 UTC, Issif commented on outputs/webex.go
> +		log.Printf("[ERROR] : webex - %v\n", err.Error())
```suggestion
		log.Printf("[ERROR] : Webex - %v\n", err.Error())
```

2024-09-03 22:09 UTC, Issif approved these changes

2024-09-03 22:09 UTC, poiana commented
LGTM label has been added.  <details>Git tree hash: d1c1e171724ca70bd871d06c25f03d8858aa0e9c</details>

2024-09-03 22:09 UTC, poiana commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/falcosecurity/falcosidekick/pull/979#pullrequestreview-2278606770" title="Approved">Issif</a>*, *<a href="https://github.com/falcosecurity/falcosidekick/pull/979#" title="Author self-approved">k0rventen</a>*

The full list of commands accepted by this bot can be found [here](https://prow.falco.org/command-help?repo=falcosecurity%2Ffalcosidekick).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/falcosecurity/falcosidekick/blob/master/OWNERS)~~ [Issif]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2024-09-05 08:39 UTC, merged